import { generatePageMetadata } from '@/lib/metadata';
import PageLayout from '../components/PageLayout';

export const metadata = generatePageMetadata({
    title: 'Disclaimer - FormatMint',
    description: 'Legal disclaimer regarding the use of FormatMint tools and content.',
    path: '/disclaimer',
});

export default function DisclaimerPage() {
    return (
        <PageLayout>
            <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
                <h1 className="text-3xl font-bold text-gray-900 mb-6">Disclaimer</h1>
                <p className="text-sm text-gray-500 mb-8">Last Updated: November 25, 2025</p>

                <div className="prose prose-blue max-w-none text-gray-600">
                    <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">General Disclaimer</h2>
                    <p className="mb-4">
                        The information provided by FormatMint ("we," "us," or "our") on https://formatmint.com (the "Site") is for general informational purposes only. All information on the Site is provided in good faith, however we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information on the Site.
                    </p>

                    <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">Tool Accuracy</h2>
                    <p className="mb-4">
                        While we strive to ensure that our tools are accurate and reliable, we cannot guarantee that they are free from errors. Users should verify the results generated by our tools before relying on them for critical tasks. We are not responsible for any errors or omissions, or for the results obtained from the use of this information.
                    </p>

                    <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">External Links Disclaimer</h2>
                    <p className="mb-4">
                        The Site may contain (or you may be sent through the Site) links to other websites or content belonging to or originating from third parties or links to websites and features in banners or other advertising. Such external links are not investigated, monitored, or checked for accuracy, adequacy, validity, reliability, availability, or completeness by us.
                    </p>

                    <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">Professional Disclaimer</h2>
                    <p className="mb-4">
                        The Site cannot and does not contain professional advice. The information is provided for general informational and educational purposes only and is not a substitute for professional advice. Accordingly, before taking any actions based upon such information, we encourage you to consult with the appropriate professionals.
                    </p>

                    <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">No Liability</h2>
                    <p className="mb-6">
                        Under no circumstance shall we have any liability to you for any loss or damage of any kind incurred as a result of the use of the site or reliance on any information provided on the site. Your use of the site and your reliance on any information on the site is solely at your own risk.
                    </p>
                </div>
            </div>
        </PageLayout>
    );
}
